---
- name: Provision AWS Infrastructure
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    key_name: "sarowar_ostad"
    region: "ap-south-1"

  tasks:
    - name: Create EC2 key pair
      ec2_key:
        name: "{{ key_name }}"
        region: "{{ region }}"
        state: present
      register: key_result

    - name: Save private key
      copy:
        content: "{{ key_result.key.private_key }}"
        dest: "~/.ssh/{{ key_name }}.pem"
        mode: '0600'
      when: key_result.changed

    - name: Create security group for web servers
      ec2_group:
        name: "web-sg"
        description: "Security group for web servers"
        region: "{{ region }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 443
            to_port: 443
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0
      register: web_sg

    - name: Launch web server
      ec2_instance:
        name: "web-server-01"
        region: "{{ region }}"
        key_name: "{{ key_name }}"
        image_id: ami-0c02fb55956c7d316  # Ubuntu 22.04
        instance_type: t3.micro
        security_groups:
          - "web-sg"
        network:
          assign_public_ip: true
        tags:
          Role: web
          Environment: production
        wait: yes
      register: web_instance

    - name: Wait for SSH to be ready
      wait_for:
        host: "{{ web_instance.instances[0].public_ip_address }}"
        port: 22
        delay: 10
        timeout: 300
      connection: local

    - name: Display instance information
      debug:
        msg: |
          Web Server IP: {{ web_instance.instances[0].public_ip_address }}
          SSH Command: ssh -i ~/.ssh/{{ key_name }}.pem ubuntu@{{ web_instance.instances[0].public_ip_address }}
