---
- name: Configure newly created server
  hosts: tag_Role_web
  gather_facts: true
  become: true

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install essential packages
      apt:
        name:
          - curl
          - net-tools
          - wget
          - vim
          - htop
          - tree
        state: present

    - name: Configure passwordless sudo for ansible
      lineinfile:
        path: /etc/sudoers.d/ansible
        line: "ubuntu ALL=(ALL) NOPASSWD:ALL"
        state: present
        validate: 'visudo -cf %s'

    - name: Install and configure Nginx
      apt:
        name: nginx
        state: present

    - name: Start and enable Nginx
      systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Create custom index page
      copy:
        content: |
          <!DOCTYPE html>
          <html>
          <head>
              <title>Welcome to Ansible!</title>
          </head>
          <body>
              <h1>Success! Ansible configured this server.</h1>
              <p>Hostname: {{ ansible_hostname }}</p>
              <p>IP: {{ ansible_default_ipv4.address }}</p>
          </body>
          </html>
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'
      notify: restart nginx

  handlers:
    - name: restart nginx
      systemd:
        name: nginx
        state: restarted
