# Application 1: Dev Team App (for dev-user testing)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-app
  namespace: dev-team
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dev-app
  template:
    metadata:
      labels:
        app: dev-app
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dev-service
  namespace: dev-team
spec:
  selector:
    app: dev-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dev-config
  namespace: dev-team
data:
  app.properties: |
    environment=development
    debug=true
---
apiVersion: v1
kind: Secret
metadata:
  name: dev-secret
  namespace: dev-team
type: Opaque
data:
  api-key: YmFzZTY0LXNlY3JldA==  # base64-secret