# serviceaccounts.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-user
  namespace: dev-team
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: application-sa
  namespace: dev-team
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitoring-user
  namespace: monitoring-team

