apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.csv: |
    p, role:read-only, applications, get, */*, allow
    p, role:developer, applications, get, */*, allow
    p, role:developer, applications, sync, */*, allow
    p, role:admin, applications, *, */*, allow
    
    g, read-only-users, role:read-only
    g, developers, role:developer
    g, argo-admins, role:admin
    
  scopes: '[groups, email]'