apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: nginx-bluegreen
spec:
  replicas: 3
  strategy:
    blueGreen:
      activeService: nginx-bluegreen-active
      previewService: nginx-bluegreen-preview
      autoPromotionEnabled: false
  selector:
    matchLabels:
      app: nginx-bluegreen
  template:
    metadata:
      labels:
        app: nginx-bluegreen
    spec:
      containers:
        - name: nginx
          image: nginx:1.27
          ports:
            - containerPort: 80
