# secure-app/secret-management.yaml
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: secure-app-demo
  annotations:
    # This tells Argo CD to ignore drift for this resource
    argocd.argoproj.io/compare-options: IgnoreExtraneous
type: Opaque
stringData:
  # These can be managed externally or via SealedSecrets/ExternalSecrets
  database-url: "postgresql://localhost:5432/secureapp"
  api-key: "initial-key-will-be-replaced"
  jwt-secret: "initial-jwt-secret"