# argocd-nginx/argo-applications/nginx-app-auto.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-demo
  namespace: argocd
  annotations:
    # This ensures immediate refresh when changes are detected
    argocd.argoproj.io/refresh-type: hard
spec:
  project: default
  source:
    repoURL: https://github.com/sarowar-alam/sarowar.git
    targetRevision: main
    path: argocd-nginx/nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    # Add retry logic for better reliability
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true