name: CI - Code Quality and Security

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]

env:
  PROJECT_DIR: "terraform-ecs-module-target-auto-scale-Node-JS-git-actions"

jobs:
  code-quality:
    name: Code Quality Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: "${{ env.PROJECT_DIR }}/package-lock.json"

      - name: Install dependencies
        run: npm ci
        working-directory: ${{ env.PROJECT_DIR }}

      - name: Run security audit
        run: npm audit --audit-level moderate
        working-directory: ${{ env.PROJECT_DIR }}

      - name: Check Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ${{ env.PROJECT_DIR }}/Dockerfile

  terraform-validation:
    name: Terraform Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format
        run: |
          cd ${{ env.PROJECT_DIR }}/terraform
          terraform fmt -check -recursive

      - name: Terraform Validate
        run: |
          cd ${{ env.PROJECT_DIR }}/terraform
          terraform validate

      - name: Terraform Security Scan
        uses: aquasecurity/tfsec-action@master
        with:
          directory: ${{ env.PROJECT_DIR }}/terraform

  build-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          cd ${{ env.PROJECT_DIR }}
          docker build -t cpu-load-test-ci:${{ github.sha }} .

      - name: Test Docker image
        run: |
          cd ${{ env.PROJECT_DIR }}
          docker run --rm \
            -e NODE_ENV=test \
            cpu-load-test-ci:${{ github.sha }} \
            node -e "console.log('Docker image test passed'); process.exit(0);"
