name: Cleanup Environments

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to cleanup"
        required: true
        type: choice
        options:
          - staging
          - production
      confirm:
        description: 'Type "DELETE" to confirm'
        required: true

jobs:
  cleanup:
    if: inputs.confirm == 'DELETE'
    name: Cleanup ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Terraform Destroy
        uses: ./.github/actions/terraform-deploy
        with:
          environment: ${{ github.event.inputs.environment }}
          terraform-action: "destroy"
          aws-region: "ap-south-1"
          project-name: "cpu-load-test-${{ github.event.inputs.environment }}"
          ecr-image-url: "dummy-value"
          auto-approve: "true"
