name: Deploy to EC2

on:
    push:
        branches: [main, master]

env:
    AWS_REGION: us-east-1 # Change to your region

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ env.AWS_REGION }}

            - name: Deploy to EC2
              run: |
                  # Add your deployment commands here
                  echo "Deploying to EC2 instance..."
                  # Example: Copy files via SSH (you'll need to set up SSH key)
                  # scp -r ./* ec2-user@your-ec2-ip:/path/to/deploy

            - name: Print success message
              run: echo "Deployment workflow completed!"
